## 1.0 Introduction

The main objective of this function is use methods for dimentionality reduction(PCA and SVD) in the same function, to test the model without import the library. The tutorial consists in use simple array with numpy and ramdom DataFrame with pandas and show the algorithm result.

## 2.0 Library installation & modules import

In [ ]:
!pip install mlutils

In [5]:
# For dimencionality reduction
from mlutils.dimensionality_reduction import dimensionality_reduction

#Others
import numpy as np
import pandas as pd

## 3.0 Using SVD  with Numpy Array

In [7]:

    df = np.array(
        [
            [-1, -1, 2, -2],
            [-2, -1, 3, -1],
            [-3, -2, 5, 1],
            [1, 1, 6, 1],
            [2, 1, 7, 1],
            [3, 2, 8, 1],
        ],
    )
    

In [8]:
df_out = dimensionality_reduction(df, decomposition_method= "SVD", k=2)
df_out

array([[ 0.34073313,  0.10864144],
       [ 0.47650997,  0.17692445],
       [ 0.70110855,  0.31684481],
       [-0.0675579 ,  0.44724498],
       [-0.17133298,  0.52770822],
       [-0.36244574,  0.61481713]])

## 4.0 Using SVD  SVD with Pandas DataFrame

In [10]:
def get_df(m, n):
    df = pd.DataFrame(np.random.rand(m,n))
    return df

In [11]:
df = get_df(6, 5)
df

0         1         2         3         4
0  0.674835  0.615498  0.799142  0.795237  0.387473
1  0.674154  0.369868  0.597868  0.592795  0.465473
2  0.702094  0.073258  0.469521  0.724243  0.071271
3  0.333447  0.772505  0.494894  0.728895  0.305274
4  0.578056  0.121787  0.033067  0.466799  0.125408
5  0.455962  0.362902  0.213305  0.002780  0.091047

In [12]:
df_out = dimensionality_reduction(df, decomposition_method= "SVD", k=3)
df_out

array([[ 0.05542333, -0.19183302, -0.57133148],
       [-0.19269507,  0.0590737 , -0.46414176],
       [ 0.28942703,  0.61429381, -0.39429179],
       [ 0.3020028 , -0.58784635, -0.45125934],
       [-0.09973038,  0.48013738, -0.25056856],
       [-0.88027099, -0.07910919, -0.19043938]])

## 5.0 Using PCA with Numpy Array

In [13]:

    df = np.array(
        [
            [-1, -1, 2, -2],
            [-2, -1, 3, -1],
            [-3, -2, 5, 1],
            [1, 1, 6, 1],
            [2, 1, 7, 1],
            [3, 2, 8, 1],
        ],
    )

In [18]:
df_out = dimensionality_reduction(df, decomposition_method= "PCA", k=2)
df_out

array([[-3.55416303, -2.01120392],
       [-3.29181646, -0.37102401],
       [-2.55517195,  2.67830462],
       [ 1.76504972,  0.04940415],
       [ 2.9974995 ,  0.00646722],
       [ 4.63860223, -0.35194805]])

## 6.0 Using PCA with Pandas DataFrame

In [14]:
def get_df(m, n):
    df = pd.DataFrame(np.random.rand(m,n))
    return df

In [15]:
get_df(6, 5)

0         1         2         3         4
0  0.174953  0.670499  0.490653  0.515824  0.851182
1  0.945670  0.240219  0.112222  0.016280  0.877027
2  0.842003  0.590167  0.635438  0.666396  0.021181
3  0.449403  0.232453  0.121792  0.707149  0.445495
4  0.405704  0.494280  0.342710  0.748343  0.161582
5  0.477807  0.886350  0.693330  0.581265  0.337138

In [16]:
df_out = dimensionality_reduction(df, decomposition_method= "PCA", k=4)
df_out

array([[-3.55416303, -2.01120392, -0.17043529, -0.12711408],
       [-3.29181646, -0.37102401,  0.15484655,  0.24054863],
       [-2.55517195,  2.67830462, -0.13828135, -0.02968419],
       [ 1.76504972,  0.04940415,  0.50760573, -0.11568939],
       [ 2.9974995 ,  0.00646722, -0.18007924, -0.19514602],
       [ 4.63860223, -0.35194805, -0.1736564 ,  0.22708504]])

## Conclusion and library advantages

This implementation is an advantage because the model was structered to be tested with both methods and choose the best methods to the model. 

## 1.1 References

[PCA Skitlearn](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html)



[SVD Sciypy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.svds.html)