# Dimencionality Reduction Function Turotial

## 1.0 Objetivo da Função.

Fazer com que os dois métodos tanto o PCA quanto o SVD possam ser chamados e testado para o modelo.




## 2.0 Importes das Bibliotecas

Basicamente a função vai importar as bibliotecas do SVD que é a do Sypy e o PCA que é pelo scikit-learn.

In [1]:
from sklearn.decomposition import PCA
from scipy.sparse.linalg import svds

## 3.0 Input e Output

A função receberá uma matriz esparsa e devolverá um array com a dimenção reduzida para o método que for chamado através do parâmetro "decoponsition_method" sendo ele uma string que pode chamar tando o "SVD"
 quanto o "PCA".

In [2]:
import os
root = '/'.join(os.getcwd().split('/')[:-1])
os.chdir(root + '/mlutils')

Importando a função

In [3]:
from dimensionality_reduction import *

## 3.1 Exemplo do output SVD

Recebendo uma Matriz esparsa aplicando um np.array:

In [4]:
import numpy as np

In [5]:
    df = np.array(
        [
            [-1, -1, 2, -2],
            [-2, -1, 3, -1],
            [-3, -2, 5, 1],
            [1, 1, 6, 1],
            [2, 1, 7, 1],
            [3, 2, 8, 1],
        ],
    )

Chamando a função com os parâmetros, recependo a matriz esparsa, o método e o "k" como o número a ser reduzido :

In [6]:
dimensionality_reduction(df, decomposition_method= "SVD", k=2)

array([[ 0.34073313,  0.10864144],
       [ 0.47650997,  0.17692445],
       [ 0.70110855,  0.31684481],
       [-0.0675579 ,  0.44724498],
       [-0.17133298,  0.52770822],
       [-0.36244574,  0.61481713]])

Trabalhando o SVD com dataframe

In [7]:
import pandas as pd

In [8]:
def get_df(m, n):
    df = pd.DataFrame(np.random.rand(m,n))
    return df

In [9]:
df = get_df(6, 5)
df

0         1         2         3         4
0  0.756971  0.977453  0.160675  0.980860  0.980663
1  0.635532  0.431642  0.130091  0.336476  0.235347
2  0.694349  0.883352  0.920999  0.223749  0.829471
3  0.503554  0.431758  0.427162  0.710970  0.776522
4  0.130192  0.930478  0.833936  0.162750  0.712340
5  0.288267  0.610093  0.312971  0.005573  0.341205

In [10]:
dimensionality_reduction(df, decomposition_method= "SVD", k=3)

array([[-0.15859257, -0.58329524,  0.55078169],
       [ 0.67326293, -0.24457787,  0.24359746],
       [ 0.33900635,  0.39415214,  0.50845174],
       [-0.38300375, -0.27053918,  0.39183812],
       [-0.4122889 ,  0.56556078,  0.41172686],
       [ 0.29994351,  0.22702859,  0.23605196]])

## 3.1 Exemplo do output PCA

Recebendo uma Matriz esparsa aplicando um np.array

In [17]:
 df = np.array(
        [
            [-1, -1, 2, -2],
            [-2, -1, 3, -1],
            [-3, -2, 5, 1],
            [1, 1, 6, 1],
            [2, 1, 7, 1],
            [3, 2, 8, 1],
        ],
    )

In [18]:
dimensionality_reduction(df, decomposition_method= "PCA", k=2)

array([[-3.55416303, -2.01120392],
       [-3.29181646, -0.37102401],
       [-2.55517195,  2.67830462],
       [ 1.76504972,  0.04940415],
       [ 2.9974995 ,  0.00646722],
       [ 4.63860223, -0.35194805]])

3.1.1 Trabalhando o PCA com DataFrame

In [19]:
def get_df(m, n):
    df = pd.DataFrame(np.random.rand(m,n))
    return df

In [20]:
get_df(6, 5)

0         1         2         3         4
0  0.982408  0.988637  0.368174  0.516153  0.331710
1  0.526197  0.447501  0.387039  0.402977  0.650552
2  0.170478  0.944127  0.650660  0.921341  0.024035
3  0.023516  0.255246  0.723774  0.680029  0.019437
4  0.188809  0.835065  0.453715  0.639758  0.290611
5  0.187785  0.004716  0.939645  0.052698  0.434568

In [21]:
dimensionality_reduction(df, decomposition_method= "PCA", k=4)

array([[-3.55416303, -2.01120392, -0.17043529, -0.12711408],
       [-3.29181646, -0.37102401,  0.15484655,  0.24054863],
       [-2.55517195,  2.67830462, -0.13828135, -0.02968419],
       [ 1.76504972,  0.04940415,  0.50760573, -0.11568939],
       [ 2.9974995 ,  0.00646722, -0.18007924, -0.19514602],
       [ 4.63860223, -0.35194805, -0.1736564 ,  0.22708504]])